from random import choice

common_sentences = [
    "How are you?",
    "I’m good, thanks.",
    "What’s up?",
    "How is it going?",
    "Hey, what’s new?",
    "Hi, how can I help you?",
    "Let me know if you need anything!",
    "Good morning/afternoon/evening!",
    "Nice to meet you!",
    "What do you do for a living?",
    "Have a sunny morning!",
    "What’s your name?",
    "It was nice talking to you!",
    "Have a great day ahead!",
    "See you later!",
    "Can I get your number/email address?",
    "I’m sorry, I don’t understand what you’re saying.",
    "Where are you from?",
    "Is there anything else I can do for you today?",
    "Let’s get together soon!",
    "What time is it now?",
    "I need your help right now.",
    "What do you think about this?",
    "Can you tell me more about it?",
    "What do you like to do in your free time?",
    "Could you please explain it to me?",
    "Can I have your opinion on this matter?",
    "What do you think is the best solution for this problem?",
    "Do you have any questions for me?",
    "I want to go on a trip.",
    "Please meet me in the afternoon.",
    "Have a safe journey!",
    "Can I reach you if I need help?",
    "What can I do to make things better?",
    "Do you have any suggestions on how to improve this situation?",
    "How did that make you feel?",
    "I feel pleasure to meet you after a long time.",
    "Have a nice weekend!",
    "How was your day?",
    "How can I reach you?",
    "Do you need any help?",
    "What do you do for a living?",
    "I’m looking for a job.",
    "We’re going to arrange a wedding party.",
    "Do you like to travel?",
    "That sounds great!",
    "Do you have any questions for me?",
    "I’m happy to help in any way I can.",
    "Can I get your phone number?",
    "What’s your email address?",
    "I’m looking forward to it.",
    "What time should we meet up?",
    "Can I have a look at it?",
    "I need to buy some groceries.",
    "Do you mind if I join in?",
    "Let’s go out for dinner tonight.",
    "What time should we meet up?",
    "I’m running late; sorry for the inconvenience.",
    "Can we reschedule our meeting for tomorrow morning?",
    "I want to make a reservation at the restaurant.",
    "Which way should I go to get there?",
    "Would you like something to drink?",
    "Can I borrow your pen, please?",
    "It’s been a pleasure talking to you.",
    "I’ll call you later this evening.",
    "I don’t understand what you said.",
    "Let me know if there’s anything else I can do for you.",
    "Can I have your email address, please?",
    "It was nice meeting you today.",
    "Have a good day!",
    "What do you think about this idea?",
    "Let’s discuss it further tomorrow.",
    "What have you been up to?",
    "It’s been a while.",
    "It’s nice to see you again.",
    "I’m doing well, thanks for asking.",
    "I’m happy to see you.",
    "It’s good to hear from you.",
    "I hope all is well with you.",
    "Can I help you with something?",
    "Do you need any assistance?",
    "Would it be possible to schedule an appointment with the manager tomorrow afternoon?",
    "Do you have any other questions or concerns?",
    "I want to get more information about this product before deciding.",
    "Are there any discounts available on this item?",
    "Could we go over the details of the contract again?",
    "Can I estimate how long it will take to complete the project?",
    "Could we arrange a call sometime next week?",
    "What are some of the benefits of using this service?",
    "Do you have any recommendations or suggestions on how to improve the process?",
    "What did you think of that experience?",
    "Is there anything else I should know about this topic?",
    "Do you have any advice for me on how to handle this situation?",
    "Would it be possible for us to meet and discuss this further in person?",
    "Could we schedule a time to discuss this issue over the phone?",
    "Can other resources or people help us with this issue further down the line if needed?",
    "What are your thoughts on the current state of affairs?",
    "What do you think would be the best way forward?",
    "Could we develop a better solution than what we currently have?",
    "What are some of the challenges we might face in implementing such a plan?",
]


def sentences(subset: int = len(common_sentences)):
    return common_sentences[:subset]


def random_sentence(sentences: list[str] = sentences()):
    return choice(sentences)


if __name__ == "__main__":
    print(sentences())
    print(random_sentence())
